name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      BROWSERSTACK_BUILD_NAME: 'playwright-${{ github.run_number }}'
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Run Playwright tests
      run: |
        xvfb-run --server-args="-screen 0 1920x1080x24" npx playwright test --workers=1
    
    - name: Run BrowserStack tests
      if: always()
      run: |
        npx playwright test --project=browserstack-windows --project=browserstack-s23-ultra
    
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: |
          playwright-report/
          test-results/
          snapshots/
        compression-level: 9
        retention-days: 30
        overwrite: true
        if-no-files-found: error
        fingerprint: true
